#---------GENERAL SETTINGS---------#
# options: chrome, firefox, edge
browser=chrome
# options: local, grid
runMode=local
# selenium Grid URL
gridURL=http://localhost:4444
# options: true, false
headless=true
# default wait time in millisecond
timeout=20000
# options: agoda, vj
environment=vj
# options:
# - `none`: return immediately
# - `eager`: return after DOMContentLoaded fires
# - `normal`: return after the load event fires on the new page
pageLoadStrategy=eager
# number of retries, maximum accepted value: 3
maxRetry=2
# options: immediate, post-suite
retryStrategy=post-suite
