#---------GENERAL SETTINGS---------#
# options: local, grid
runMode=local
# selenium Grid URL
gridURL=http://localhost:4444
# options:
# - `none`: return immediately
# - `eager`: return after DOMContentLoaded fires
# - `normal`: return after the load event fires on the new page
pageLoadStrategy=eager
